# Generated by Django 5.1.1 on 2024-09-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_categoria_pub_date_remove_producto_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
